(function() {    var toc =  [
{"name":"関連付けられてないPMIを検出 (Avoid Non-Associated PMI)","type":"item","tilePath":"","description":"","url":"Common/General/Avoid_Non-Associated_PMI.htm"},
{"name":"面取りされた穴エッジ (Chamfered Hole Edges)","type":"item","tilePath":"","description":"","url":"Common/General/chamfered_hole_edges.htm"},
{"name":"フィレット半径 (Fillet Radius)","type":"item","tilePath":"","description":"","url":"Common/General/fillet_radius_generic.htm"},
{"name":"最大平面度公差 (Maximum Flatness Tolerance)","type":"item","tilePath":"","description":"","url":"Common/General/Maximum_Flatness_Tolerance.htm"},
{"name":"ドリル貫通部最小肉厚 (Minimum Drill Breakout Wall Thickness)","type":"item","tilePath":"","description":"","url":"Common/General/min_drill_break_thk.htm"},
{"name":"ボスの最小肉厚 (Minimum Wall Thickness for Boss)","type":"item","tilePath":"","description":"","url":"Common/General/min_wall_thk_for_boss.htm"},
{"name":"材料に基づく部品点数の削減 (Part Count Reduction - Material Based)","type":"item","tilePath":"","description":"","url":"Common/General/part_count_reduction_material_based.htm"},
{"name":"推奨角度公差 (Recommended Angularity Tolerance)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Angularity_Tolerance.htm"},
{"name":"推奨真円度公差 (Recommended Circularity Tolerance)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Circularity_Tolerance.htm"},
{"name":"推奨皿穴寸法 (Recommended Countersink Hole Parameters)","type":"item","tilePath":"","description":"","url":"Common/General/recommended_countersink_hole_parameters.htm"},
{"name":"推奨円筒度公差 (Recommended Cylindricity Tolerance)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Cylindricity_Tolerance.htm"},
{"name":"推奨寸法記入法 (Recommended Dimensioning Method)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Dimensioning_Method.htm"},
{"name":"推奨平面度公差 (Recommended Flatness Tolerance)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Flatness_Tolerance.htm"},
{"name":"推奨平行度公差 (Recommended Parallelism Tolerance)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Parallelism_Tolerance.htm"},
{"name":"推奨直角度公差 (Recommended Perpendicularity Tolerance)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Perpendicularity_Tolerance.htm"},
{"name":"推奨標準ネジサイズ (Recommended Standard Thread Sizes)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Standard_Thread_Sizes.htm"},
{"name":"推奨真直度公差 (Recommended Straightness Tolerance)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Straightness_Tolerance.htm"},
{"name":"外ネジ推奨ネジクラス (Recommended Thread Class - External Threads)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Thread_Class_External_Threads.htm"},
{"name":"内ネジ推奨ネジクラス (Recommended Thread Class - Internal Threads)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Thread_Class_Internal_Threads.htm"},
{"name":"推奨ネジ単位 (Recommended Thread Unit)","type":"item","tilePath":"","description":"","url":"Common/General/Recommended_Thread_Unit.htm"},
{"name":"肉厚チェック (Thickness Check)","type":"item","tilePath":"","description":"","url":"Common/General/thickness_check.htm"},
{"name":"穴のネジ逃げ (Thread Relief for Hole)","type":"item","tilePath":"","description":"","url":"Common/General/thread_relief_for_hole.htm"},
{"name":"推奨材料の使用 (Use Preferred Materials)","type":"item","tilePath":"","description":"","url":"Common/General/use_preferred_materials.htm"}];    
window.rh.model.publish(rh.consts('KEY_TEMP_DATA'), toc, { sync:true });    })();