(function() {    var toc =  [
{"name":"ボスのリセス部寸法 (Boss Recess Parameters)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Boss_Recess_Parameters.htm"},
{"name":"ボス間隔 (Boss Spacing)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Boss_Spacing.htm"},
{"name":"ボス内のコア穴の底部半径 (Cored Hole Radius in Boss)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Cored_Hole_Radius_in_Boss.htm"},
{"name":"高さに基づく抜き勾配 (Draft Angle Based on Height)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Draft_Angle_Based_on_Height.htm"},
{"name":"穴深さと直径の比率 (Hole Depth to Diameter Ratio)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Hole_Depth_to_Diameter_Ratio.htm"},
{"name":"最大カットアウト面積 (Maximum Cutout Area)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/maximum_cutout_area.htm"},
{"name":"リブ肉厚に対する最大リブ高さ (Maximum Rib Height for Rib Thickness)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/rib_height_for_rib_thickness.htm"},
{"name":"最小抜き勾配 (Minimum Draft Angle)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/minimum_draft_angle.htm"},
{"name":"刻印に対する最小抜き勾配 (Minimum Draft Angle for Text)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Minimum_Draft_Angle_for_Text.htm"},
{"name":"ボスの最小抜き勾配 (Minimum Draft for Bosses)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Minimum_Draft_For_Bosses.htm"},
{"name":"リブの最小抜き勾配 (Minimum Draft for Ribs)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Minimum_Draft_For_Ribs.htm"},
{"name":"リブの最小エッジ半径 (Minimum Edge Radius for Rib)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/rib_edge_radius.htm"},
{"name":"ボス根本部の最小半径 (Minimum Radius at Base of Boss)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/minimium_radius_at_base_of_boss.htm"},
{"name":"リブ根元部の最小半径 (Minimum Radius at Base of Rib) ","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Radius_at_Base_of_Ribs.htm"},
{"name":"ボス先端部の最小半径 (Minimum Radius at Tip of Boss)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/minimium_radius_at_tip_of_boss.htm"},
{"name":"金型壁厚 (Mold Wall Thickness)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/mold_wall_thickness.htm"},
{"name":"リップの推奨底部半径 (Recommended Bottom Radius for Lip)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Recommended_Bottom_Radius_for_Lip.htm"},
{"name":"推奨ボス寸法 (Recommended Boss Parameters)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Recommended_Boss_Parameters.htm"},
{"name":"推奨コーナー半径 (Recommended Corner Radius)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/recommended_corner_radius.htm"},
{"name":"推奨成形公差 (Recommended Molding Tolerances)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Recommended_Molding_Tolerances.htm"},
{"name":"推奨ピン直径 (Recommended Pin Diameter)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Recommended_Pin_Diameter.htm"},
{"name":"推奨リブ寸法 (Recommended Rib Parameters)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/recommended_rib_parameters.htm"},
{"name":"推奨刻印高さ (Recommended Text Height)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Recommended_Text_Height.htm"},
{"name":"リセスボスのリブ寸法 (Rib Parameters for Recessed Boss)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Rib_Parameters_for_Recessed_Boss.htm"},
{"name":"リブ補強チェック (Rib Reinforcement Check)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/rib_reinforcement_check.htm"},
{"name":"シャットオフ寸法 (Shut-off Parameters)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Shut-off_Parameters.htm"},
{"name":"カットアウト間隔 (Spacing between Cutouts)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Spacing_Between_Holes.htm"},
{"name":"急激な製品肉厚変化 (Sudden Wall Thickness Variation)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/sudden_wall_thickness_variation.htm"},
{"name":"リブ先端部の肉厚 (Thickness at Tip of Rib)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Thickness_at_Tip_of_Rib.htm"},
{"name":"アンダーカット検出 (Undercut Detection)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/undercut_detection.htm"},
{"name":"均一な製品肉厚 (Uniform Wall Thickness)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/uniform_wall_thickness.htm"},
{"name":"製品肉厚のばらつき (Wall Thickness Variation)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/wall_thickness_variation.htm"},
{"name":"長尺コア用サポート穴チェック (Check Support Hole for Long Cores)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Check_Support_Hole_for_Long_Cores.htm"},
{"name":"パーティングライン周辺のフィレット回避 (Avoid Fillet Radius Around Parting Line)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Avoid_Fillet_Radius_Around_Parting_Line.htm"},
{"name":"長尺コア用サポート穴の最小径 (Minimum Diameter of Support Hole for Long Cores)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Minimum_Diameter_of_Support_Hole_for_Long_Cores.htm"},
{"name":"ゲート位置の最小肉厚 (Minimum Wall Thickness for Gate Location)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Minimum_Wall_Thickness_for_Gate_Location.htm"},
{"name":"金型加工用リブパラメータ (Rib Parameters for Mold Machining)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Rib_Parameters_for_Mold_Machining.htm"},
{"name":"長尺コア用推奨インターロックパラメータ (Recommended Interlock Parameters for Long Cores)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Recommended_Interlock_Parameters_for_Long_Cores.htm"},
{"name":"長尺コア用サポート穴の最大間隔 (Maximum Support Hole Distance for Long Cores)","type":"item","tilePath":"","description":"","url":"Common/Injection_Molding/Maximum_Support_Hole_Distance_for_Long_Cores.htm"},];    
window.rh.model.publish(rh.consts('KEY_TEMP_DATA'), toc, { sync:true });    })();