(function() {    var toc =  [
{"name":"Bend Relief(曲げリリーフ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Bend_Relief.htm"},
{"name":"Bridge Lance Spacing(ブリッジランス間隔)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Bridge_Lance_Spacing.htm"},
{"name":"Bridge Lance with Extruded Hole(押し出し穴付きブリッジランス)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Bridge_Lance_with_Extruded_Hole.htm"},
{"name":"Card Guide Form to Bend Distance(カードガイド成形と曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Card_Guide_Form_to_Bend_Distance.htm"},
{"name":"Card Guide Form Parameters(カードガイド成形寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Card_Guide_Form_Parameters.htm"},
{"name":"Closed Hem Parameters(クローズドヘム寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Closed_Hem_Parameters.htm"},
{"name":"Closed Hem with a Bend Parameters(曲げ付きクローズドヘム寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Closed_Hem_with_a_Bend_Parameters.htm"},
{"name":"Counterbore Hole Distance to Part Edge(座ぐり穴と部品エッジ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/counterbore_hole_distance_to_part_edge.htm"},
{"name":"Counterbore Hole to Bend Distance(座ぐり穴と曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/counterbore_hole_to_bend_distance.htm"},
{"name":"Counterbore Hole Spacing(座ぐり穴間隔)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/counterbore_hole_spacing.htm"},
{"name":"Countersink Hole Distance to Form(皿穴と成形形状の距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Countersink_Hole_Distance_To_Form.htm"},
{"name":"Countersink Hole Distance to Part Edge(皿穴と部品エッジの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/countersink_hole_distance_to_part_edge.htm"},
{"name":"Countersink Hole to Bend Distance(皿穴と曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/countersink_hole_to_bend_distance.htm"},
{"name":"Countersink Hole Spacing(皿穴間隔)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/countersink_hole_spacing.htm"},
{"name":"Curl Distance to Bends(カールと曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Curl_Distance_To_Bends.htm"},
{"name":"Curl Distance to Cutouts(カールとカットアウト距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Curl_Distance_To_Cutouts.htm"},
{"name":"Cutout Distance to Part Edge(カットアウトと部品エッジ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_distance_to_part_edge.htm"},
{"name":"Cutout Distance to Part Edge - Based on Line Length(カットアウトと部品エッジ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_distance_to_part_edge(LineLengthBased).htm"},
{"name":"Cutout to Bend Distance(カットアウトと曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_to_bend_distance.htm"},
{"name":"Cutout to Bend Distance - Based on Line Length(カットアウトと曲げ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_distance_to_bend(LineLengthBased).htm"},
{"name":"Cutout to Part Edge Distance - Based on Cutout Length(カットアウト長さに基づくエッジ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Cutout_to_Part_Edge_Distance.htm"},
{"name":"Dowel Distance to Bends(ダウエルと曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_distance_to_bends.htm"},
{"name":"Dowel Distance to Cutouts(ダウエルとカットアウトの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_distance_to_cutouts.htm"},
{"name":"Dowel Distance to Part Edge(ダウエルと部品エッジの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_distance_to_part_edge.htm"},
{"name":"Dowel Outer Diameter(ダウエル外径)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_outer_diameter.htm"},
{"name":"Dowel Outer Diameter Height(ダウエル外径高さ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_height.htm"},
{"name":"Dowel Spacing(ダウエル間隔)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/dowel_spacing.htm"},
{"name":"Emboss Distance to Cutouts(エンボスとカットアウト距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_to_Cutouts.htm"},
{"name":"Emboss to Bend Distance(エンボスと曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_To_Bend_Distance.htm"},
{"name":"Emboss to Part Edge Distance(エンボスと部品エッジの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_To_Edge_Distance.htm"},
{"name":"Emboss Spacing(エンボス間隔)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_Spacing.htm"},
{"name":"Emboss with Extruded Hole Parameters(押し出し穴付きエンボス寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Emboss_with_Extruded_Hole_Parameters.htm"},
{"name":"Extruded Form Distance to Cutouts(押し出し成形とカットアウトの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_Distance_To_Cutouts.htm"},
{"name":"Extruded Form Distance to Part Edge(押し出し成形と部品エッジ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_Distance_To_Part_Edge.htm"},
{"name":"Extruded Form Parameters(押し出し成形寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_Parameters.htm"},
{"name":"Extruded Form to Bend Distance(押し出し成形と曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_to_Bend_.htm"},
{"name":"Extruded Form Spacing(押し出し成形の間隔)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Extruded_Form_Spacing.htm"},
{"name":"Extruded Hole Distance to Bends(押し出し穴と曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_distance_to_bends.htm"},
{"name":"Extruded Hole Distance to Cutouts(押し出し穴とカットアウト距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_distance_to_cutout.htm"},
{"name":"Extruded Hole Distance to Part Edge(押し出し穴と部品エッジ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_distance_to_part_edge.htm"},
{"name":"Extruded Hole Height(押し出し穴高さ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_height.htm"},
{"name":"Extruded Hole Inner Diameter(押し出し穴の内径)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_inner_diameter.htm"},
{"name":"Extruded Hole Parameters(押し出し穴パラメータ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_parameters.htm"},
{"name":"Extruded Hole Spacing(押し出し穴の間隔)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/burring_hole_spacing.htm"},
{"name":"Feature Direction for Fabrication(製造方向(フィーチャ))","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/feature_direction_for_fabrication.htm"},
{"name":"Flange Interference Check(フランジ干渉チェック)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/flange_interference_check.htm"},
{"name":"Gusset Parameter(ガセット寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Gusset_Parameter.htm"},
{"name":"Gusset Spacing(ガセット間隔)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Gusset_Spacing.htm"},
{"name":"Half-Shear Parameters(ハーフシア寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/half_shear_Parameters.htm"},
{"name":"Hem Distance to Bends(ヘムと曲げ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Hem_Distance_To_Bends.htm"},
{"name":"Hem Distance to Cutouts(ヘムとカットアウト距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Hem_Distance_To_Cutouts.htm"},
{"name":"Hem Distance to Form(ヘムと成形形状の距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Hem_Distance_To_Form.htm"},
{"name":"Hem Spacing(ヘム間隔)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Hem_Spacing.htm"},
{"name":"Hole Distance to Bends(穴と曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/hole_distance_to_bends.htm"},
{"name":"Hole to Part Edge Distance(穴と部品エッジ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/hole_to_part_edge_distance.htm"},
{"name":"Interference in Flat Pattern(フラットパターンの干渉)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/interference_in_flat_pattern.htm"},
{"name":"Knife Edge(ナイフエッジ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/knife_edge.htm"},
{"name":"Maximum Bridge Angle(ブリッジの最大角度)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_bridge_angle.htm"},
{"name":"Maximum Bridge Height(ブリッジの最大高さ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_bridge_height.htm"},
{"name":"Maximum Depth of Counterbore(座ぐり穴の最大深さ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_depth_of_counterbore.htm"},
{"name":"Maximum Depth of Countersink(皿穴の最大深さ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_depth_of_countersink.htm"},
{"name":"Maximum Embossment Depth(エンボス最大深さ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/maximum_embossment_depth.htm"},
{"name":"Minimum Bend Radius(最小曲げ半径)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_bend_radius.htm"},
{"name":"Minimum Bridge Width(ブリッジの最小幅)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_bridge_width.htm"},
{"name":"Minimum Corner Radius(最小コーナー半径)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_corner_radius.htm"},
{"name":"Minimum Corner Radius for Hem(ヘム最小コーナー半径)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_corner_radius_for_hem.htm"},
{"name":"Minimum Distance between Cutouts(カットアウト間の最小距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/min_dist_bet_cutouts.htm"},
{"name":"Minimum Distance between Cutouts - Based on Line Length(カットアウト間距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/cutout_distance_between_cutouts(LineLengthBased).htm"},
{"name":"Minimum Distance between Dimples(ディンプル間距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_between_dimples.htm"},
{"name":"Minimum Distance between Notches(ノッチ間の最小距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_notch_to_notch_distance.htm"},
{"name":"Minimum Distance between Perforated Cutouts(穿孔カットアウト間の最小距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Minimum_Distance_between_Perforated_Cutouts.htm"},
{"name":"Minimum Distance from Bend to a Parallel Slot(長穴と曲げの最小平行距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/min_dist_bend_to_parallel_slot.htm"},
{"name":"Minimum Distance from Dimple to Bend(ディンプルと曲げ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_from_dimple_to_bend.htm"},
{"name":"Minimum Distance from Dimple to Cutout(ディンプルとカットアウト距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_from_dimple_to_cutout.htm"},
{"name":"Minimum Distance from Dimple to Hole(ディンプルと穴距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_from_dimple_to_hole.htm"},
{"name":"Minimum Distance from Dimple to Part Edge(ディンプルと部品エッジ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_distance_from_dimple_to_partedge.htm"},
{"name":"Minimum Distance from Edge of Part to a Parallel Slot(長穴とエッジの最小平行距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/min_dist_edge_to_parallel_slot.htm"},
{"name":"Minimum Flange Height(最小フランジ高さ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_flange_height.htm"},
{"name":"Minimum Hole Diameter(最小穴径)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_hole_diameter.htm"},
{"name":"Minimum Width of a Slot(長穴の最小幅)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/min_width_of_slot.htm"},
{"name":"Minimum Width of Cutout(カットアウトの最小幅)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_width_of_cutout.htm"},
{"name":"Multiple Bends in Same Direction(同一方向の複数曲げ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/multiple_bends_in_same_direction.htm"},
{"name":"Notch Parameters(ノッチ寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/notch_parameters.htm"},
{"name":"Notch to Bend Distance(ノッチと曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/minimum_notch_to_bend_distance.htm"},
{"name":"Notch to Bend Distance - Based on Notch Length(ノッチ長さに基づくノッチと曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Notch_to_Bend_Distance_(Notch_Length_Based).htm"},
{"name":"Open Hem(オープンヘム)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/open_hem.htm"},
{"name":"Part Count Reduction - Thickness Based(パーツ削減(板厚ベース))","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/part_count_reduction_thickness_based.htm"},
{"name":"Preferred Sheet Sizes(推奨板材サイズ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/preferred_sheet_sizes.htm"},
{"name":"Recommended Enclosure Size(推奨エンクロージャサイズ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Recommended_Enclosure_size.htm"},
{"name":"Recommended Flange Parameters(推奨フランジ寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/recommended_flange_parameters.htm"},
{"name":"Recommended Hole Distance Tolerance(推奨穴距離公差)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Recommended_Hole_Distance_Tolerance.htm"},
{"name":"Recommended Punch Parameters(推奨パンチ寸法)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Recommended_punch_parameters.htm"},
{"name":"Recommended Spoon Parameters(推奨スプーン形状パラメータ)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Recommended_Spoon_Parameters.htm"},
{"name":"Relief to Bend Distance(リリーフと曲げの距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Relief_To_Bend_Distance.htm"},
{"name":"Rolled Hem(ロールドヘム)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/curl_radius.htm"},
{"name":"Rolled Hem to Hole Edge Distance(ロールドヘムと穴エッジ距離)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/curl_to_hole_edge_spacing.htm"},
{"name":"Sheet Metal Modeling Practice(板金モデリング推奨事項)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Sheet_Metal_Modeling_Practice.htm"},
{"name":"Tear Drop Hem(ティアドロップヘム)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/tear_drop.htm"},
{"name":"Use Common Bend Radius(共通曲げ半径の使用)","type":"item","tilePath":"","description":"","url":"Common/Sheet_Metal/Use_Common_Bend_Radius.htm"}];    
window.rh.model.publish(rh.consts('KEY_TEMP_DATA'), toc, { sync:true });    })();